<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Meghas-MBP" ignored="0" name="Command line test" tests="4" failures="1" timestamp="2020-05-06T01:58:19 EDT" time="0.048" errors="0">
  <testcase name="div" time="0.006" classname="com.qa.tests.DemoTest">
    <failure type="java.lang.AssertionError" message="expected [0] but found [2]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [2]
at com.qa.tests.DemoTest.div(DemoTest.java:32)
at java.util.ArrayList.forEach(ArrayList.java:1257)
... Removed 41 stack frames]]>
    </failure>
  </testcase> <!-- div -->
  <testcase name="multi" time="0.0" classname="com.qa.tests.DemoTest"/>
  <testcase name="sub" time="0.0" classname="com.qa.tests.DemoTest"/>
  <testcase name="sum" time="0.0" classname="com.qa.tests.DemoTest"/>
</testsuite> <!-- Command line test -->
